export const WIDGET_TYPES = {
    ACCORDION: "accordion",
    ADVISORY: "advisory",
    ALARM: "alarm",
    ALERT: "alert",
    CAROUSEL: "carousel",
    GAUGE: "gauge",
    GAUGE_ALERT: "gauge_alert",
    GAUGE_CYLINDER: "gauge_cylinder",
    FLEET_DASH_PARAMETERS_FILTER: "fleet_dash_parameters_filter",
    FLEET_DASH_ALL_VESSELS_FILTER: "fleet_dash_all_vessels_filter",
    ALL_VESSEL_LEAFLET_MAP: "all_vessel_leaflet_map",
    ALL_VESSEL_PARAMETERS_INFO_PANEL: "all_vessel_parameters_info_panel",
    LEAFLET_MAP: "leaflet_map",
    NANJING_ME_TABLE: "nanjing_me_table",
    ASIA_ME_TABLE: "asia_me_table",
    SPARINDUS_ME_TABLE: "sparindus_me_table",
    SPARINDUS_ME_ACCORDION: "sparindus_me_accordion",
    MAIN_ENGINE_CYLINDER: "main_engine_cylinder",
    XPRESS_MAIN_ENGINE_CYLINDER: "xpress_main_engine_cylinder",
    BATAVIA_ME_TABLE: "batavia_me_table",
    BATAVIA_MAIN_ENGINE_CYLINDER: "batavia_main_engine_cylinder",
    BATAVIA_MAIN_ENGINE_ACCORDION: "batavia_main_engine_accordion",
    ASIA_MAIN_ENGINE_CYLINDER: "asia_main_engine_cylinder",
    Digital_Alarm_Table: "digital_alarm_table",
    MAIN_ENGINE_TABLE: "main_engine_table",
    XPRESS_MAIN_ENGINE_ACCORDION: "xpress_main_engine_accordion",
    ASIA_MAIN_ENGINE_ACCORDION: "asia_main_engine_accordion",
    SYSTEM_TABLE: "system_table",
    TEXT_CARD: "text_card",
    NANJING_MAIN_ENGINE_ACCORDION: "nanjing_main_engine_accordion",
    VESSEL_INFORMATION_ACCORDION: "vessel_information_accordion",
    VESSEL_PROGRESS_BAR: "vessel_progress_bar",
    CUSTOM_GAUGE_WITH_SPARK_BAR_AND_LABEL: "custom_gauge_with_spark_bar_and_label",
    CUSTOM_GAUGE: "custom_gauge",
    DASH_HOME_3_CAROUSEL: "dash_home_3_carousel",
    DASH_HOME_INFORMATION_CAROUSEL: "dash_home_information_carousel",
    MAIN_ENGINE_ACCORDION: "main_engine_accordion",
    CUSTOM_BAR_GAUGE: "custom_bar_gauge",
    CUSTOM_BAR_GAUGE_LIST: "custom_bar_gauge_list",
    OBSERVANT: "observant",
    MRV_INFORMATIONAL_PANEL1: "mrv_informational_panel1",
    MRV_FILTER_PANEL: "mrv_filter_panel",
    BAR_CHART: "bar_chart",
    GAUGES_HOME_GAUGES_STRIPE: "gauges_home_gauges_stripe",
    FULL_SCREEN_COMPASS:"fullScreen_compass",
    COMPASS_SCREEN_WIND_MAP:"leaflet_map_compass",
  /*  Task No-SSH-18
    Dev Name:Yogesh Chavan
    Desc:-Multiline graph*/
    MULTI_LINE_GRAPH:"multiline_graph",
    NON_REPORT_DATA_DASHBOARD:"noonreportdata",
    CII_FILTER_PANEL:"cii_filter_panel"
    
};
